/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author crism
 */
public class EstructurasControl extends javax.swing.JFrame {

    /**
     * Creates new form EstructurasControl
     */
    public EstructurasControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnIf = new javax.swing.JButton();
        btnSwitch = new javax.swing.JButton();
        btnFor = new javax.swing.JButton();
        btndowhile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Estructuras de control Guerrero");

        btnIf.setText("Estructura selectiva if");
        btnIf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIfActionPerformed(evt);
            }
        });

        btnSwitch.setText("Estructura selectiva switch");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnFor.setText("Estructura ciclica for");

        btndowhile.setText("Estructura ciclica dowhile");
        btndowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndowhileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(btndowhile)
                    .addComponent(btnFor)
                    .addComponent(btnSwitch)
                    .addComponent(btnIf))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitulo)
                .addGap(42, 42, 42)
                .addComponent(btnIf)
                .addGap(18, 18, 18)
                .addComponent(btnSwitch)
                .addGap(18, 18, 18)
                .addComponent(btnFor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndowhile)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndowhileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndowhileActionPerformed

    private void btnIfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIfActionPerformed
        //Entrada   Declaracion de variables y entrada de datos
        String ventanaEdad=JOptionPane.showInputDialog("Captura edad:");
        int edad=Integer.parseInt(ventanaEdad);
        //Proceso-salida
        if (edad>=18) {//Para condicion verdadera
                JOptionPane.showMessageDialog(null, "Eres mayor de edad \n"+edad);
            } else {//Para condicion falsa
            JOptionPane.showMessageDialog(null, "Eres menor de edad \n"+edad);
            }
    }//GEN-LAST:event_btnIfActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        //Entrada 
        String ventanaMenu=JOptionPane.showInputDialog("Menu Video Juego Guerrrero \n"
                                                       + "Captura numero entero \n"
                                                       + "1. Jugar \n"
                                                       + "2. Pausar \n"
                                                       + "3. Salir \n");
        int menu=Integer.parseInt(ventanaMenu);
        //Proceso-salida
        switch (menu) {//Inicia switch
            case 1:JOptionPane.showMessageDialog(null, "Seleccionaste "+menu+": Inicia partida");break;
            case 2:JOptionPane.showMessageDialog(null, "Seleccionaste "+menu+": Juego detenido");break;
            case 3:JOptionPane.showMessageDialog(null, "Seleccionaste "+menu+": Finalizo el juego");break;
        default:JOptionPane.showMessageDialog(null, "Seleccionaste "+menu+": Opcion invalida solo tengo 1,2,3");break;
        }//Termina switch
    }//GEN-LAST:event_btnSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstructurasControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstructurasControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstructurasControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstructurasControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstructurasControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFor;
    private javax.swing.JButton btnIf;
    private javax.swing.JButton btnSwitch;
    private javax.swing.JButton btndowhile;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
